services:
  testdb:
    image: postgres:16.3-alpine3.20
    env_file:
      - .env.development.local
    ports:
      - "5432:5432"
    volumes:
      - testdb:/var/lib/postgresql/data
volumes:
  testdb:
